### ISSUE TITLE
Black Camera

### ISSUE THREAD

**Issue by JohnLouderback** [GreyGolem/DitheringMegapack#1]
Full disclosure - I'm very new to Unity. I'm very technical and a C# developer with a decent understanding of shaders, though more so HLSL than Unity's format. That all said, I'm experiencing a black screen with the dithering shader when applied to the camera.  Perhaps I'm missing something obvious, but I figured this would be pretty plug-and-play. Any ideas?

**Comment by GreyGolem** [comment]
Could you please provide more details as to how to reproduce your issue?

What version of Unity are you using? Beta or stable? Does anything appear in the debug log?
